name: Lint commit messages
on: [push]
jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Install gitlint
      run: sudo apt-get update && sudo apt-get install -y gitlint
    - name: Lint commits
      run: gitlint --commits ${{ github.head_ref || github.ref_name }}
