name: Run pytests
on: [push]
jobs:
  test:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: python3.10 -m pip install -r requirements.txt
    - name: Install pytest
      run: python3.10 -m pip install pytest
    - name: Run pytests
      run: timeout 300 python3.10 -m pytest

