name: Typecheck python
on: [push]
jobs:
  typecheck:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: python3.10 -m pip install -r requirements.txt
    - name: Install mypy
      run: python3.10 -m pip install mypy
    - name: Typecheck python
      run: mypy .
